version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Ajith@123
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - 5433:5432
  app:
    build: .
    ports: 
      - 13000:3000
    volumes:
      - "./:/app:rw"
    